Add OVN IC CI
Fixes: submariner-io/enhancements#209
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

diff --git a/scripts/shared/lib/clusters_kind b/scripts/shared/lib/clusters_kind
--- a/scripts/shared/lib/clusters_kind
+++ b/scripts/shared/lib/clusters_kind
@@ -191,18 +191,13 @@ EOF
 }
 
 function deploy_kind_ovn(){
-    local OVN_SRC_IMAGE="ghcr.io/ovn-org/ovn-kubernetes/ovn-kube-f:master"
     export K8s_VERSION="${K8S_VERSION}"
     export NET_CIDR_IPV4="${cluster_CIDRs[${cluster}]}"
     export SVC_CIDR_IPV4="${service_CIDRs[${cluster}]}"
     export KIND_CLUSTER_NAME="${cluster}"
 
-    export OVN_IMAGE="localhost:5000/ovn-daemonset-f:latest"
-    docker pull "${OVN_SRC_IMAGE}"
-    docker tag "${OVN_SRC_IMAGE}" "${OVN_IMAGE}"
-    docker push "${OVN_IMAGE}"
-
-    delete_cluster_on_fail ./ovn-kubernetes/contrib/kind.sh -ov "$OVN_IMAGE" -cn "${KIND_CLUSTER_NAME}" -ric -lr -dd "${KIND_CLUSTER_NAME}.local"
+    [[ "$OVN_IC" = true ]] && delete_cluster_on_fail ./ovn-kubernetes/contrib/kind.sh -ov "$OVN_IMAGE" -cn "${KIND_CLUSTER_NAME}" -ric -ic -npz 1 -wk 3 -lr -dd "${KIND_CLUSTER_NAME}.local"
+    [[ "$OVN_IC" != true ]] && delete_cluster_on_fail ./ovn-kubernetes/contrib/kind.sh -ov "$OVN_IMAGE" -cn "${KIND_CLUSTER_NAME}" -ric -lr -dd "${KIND_CLUSTER_NAME}.local"
 
     [[ "$AIR_GAPPED" = true ]] && air_gap_iptables
 }
@@ -229,6 +224,7 @@ function run_local_registry() {
         for image in "${local_image_list[@]}"; do
             docker push "${image}" || echo "Failed to push ${image@Q} to registry."
         done
+        return 0 # Avoid returning non-zero if there are no local images
     fi
 }
 
@@ -247,7 +243,7 @@ function provider_failed() {
 # ovn-kubernetes repo from master in order to access the required
 # kind scripts, and manifest generation templates.
 function download_ovnk() {
-    echo "Cloning ovn-kubernetes from source"
+    echo "Cloning ovn-kubernetes source"
     mkdir -p ovn-kubernetes
     # We only need the contrib directory, use a sparse checkout
     (
@@ -264,11 +260,47 @@ function download_ovnk() {
     )
 }
 
+function prepare_ovn_ic() {
+    echo "Building ovn-kubernetes with interconnect (OVN-IC) from source"
+    rm -rf ovn-kubernetes || true
+    git clone https://github.com/ovn-org/ovn-kubernetes
+    pushd ovn-kubernetes || exit
+
+    pushd go-controller || exit
+    make
+    popd || exit
+
+    cp go-controller/_output/go/bin/* dist/images
+
+    pushd dist/images || exit
+    echo "ref: $(git rev-parse --symbolic-full-name HEAD) commit: $(git rev-parse HEAD)" > git_info
+    docker build -t "${OVN_IMAGE}" -f Dockerfile.fedora .
+    docker push "${OVN_IMAGE}"
+    popd || exit
+
+    popd || exit
+}
+
+function prepare_ovn() {
+    export OVN_IMAGE="localhost:5000/ovn-daemonset-f:latest"
+
+    if [[ "$OVN_IC" = true ]]; then
+        prepare_ovn_ic
+    else
+        download_ovnk
+
+        local OVN_SRC_IMAGE="ghcr.io/ovn-org/ovn-kubernetes/ovn-kube-f:master"
+        docker pull "${OVN_SRC_IMAGE}"
+        docker tag "${OVN_SRC_IMAGE}" "${OVN_IMAGE}"
+        docker push "${OVN_IMAGE}"
+    fi
+}
+
 function provider_prepare() {
     [[ -z "${K8S_VERSION}" ]] && K8S_VERSION="${DEFAULT_K8S_VERSION}"
     [[ -n "${kind_k8s_versions[$K8S_VERSION]}" ]] && K8S_VERSION="${kind_k8s_versions[$K8S_VERSION]}"
 
     download_kind
-    [[ "${cluster_cni[*]}" != *"ovn"* ]] || download_ovnk
     run_local_registry
+    [[ "${cluster_cni[*]}" != *"ovn"* ]] || prepare_ovn
 }
